#!/usr/bin/env python3
"""
Regenerate llms-full.txt from the scraped docs/ tree.

The index is derived, never hand-edited: run this after scrape_ninjatrader_docs.py
so the topic list, counts, and file paths cannot drift away from what is on disk.

Pages are grouped by product namespace and, within the desktop docs, bucketed by
the section headings the pages themselves use ("Property Value", "Method Return
Value", ...). That keeps the taxonomy grounded in the source rather than in a
hand-maintained list that rots as the site changes.
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List, NamedTuple

# Rendered in this order; anything unmatched lands in the last bucket.
DESKTOP_CATEGORIES = [
    "Built-in Indicators",
    "Classes",
    "Methods",
    "Properties",
    "SharpDX",
    "Guides & Concepts",
]

# Headings for the non-desktop products. Namespaces that appear on the site
# later are still rendered, under their own name, rather than silently dropped.
NAMESPACE_SECTIONS = {
    "web": "Web SDK (JavaScript indicators for NinjaTrader Web & Mobile)",
    "ecosystem": "Ecosystem API (vendor licensing)",
}


class Topic(NamedTuple):
    title: str
    path: str
    namespace: str
    category: str


def read_frontmatter(text: str) -> Dict[str, str]:
    match = re.match(r"---\n(.*?)\n---\n", text, re.S)
    if not match:
        return {}
    fields = {}
    for line in match.group(1).split("\n"):
        key, _, value = line.partition(":")
        if value:
            fields[key.strip()] = value.strip()
    return fields


def classify_desktop(title: str, headings: List[str]) -> str:
    """Bucket a desktop page using the section headings it actually contains."""
    if title.startswith("SharpDX"):
        return "SharpDX"
    if "Source Code" in headings and "Description" in headings:
        return "Built-in Indicators"
    if title.endswith("Class") or "Methods and Properties" in headings:
        return "Classes"
    if {"Method Return Value", "Method Parameters"} & set(headings) or title.endswith("()"):
        return "Methods"
    if "Property Value" in headings:
        return "Properties"
    return "Guides & Concepts"


def collect_topics(docs_dir: Path) -> List[Topic]:
    topics = []
    for path in sorted(docs_dir.rglob("*.md")):
        text = path.read_text(encoding="utf-8")
        fields = read_frontmatter(text)
        if not fields:
            continue
        headings = re.findall(r"(?m)^##\s+(.+?)\s*$", text)
        namespace = fields.get("namespace", "")
        title = fields.get("title", path.stem)
        category = classify_desktop(title, headings) if namespace == "desktop" else ""
        topics.append(Topic(
            title=title,
            path=str(path.relative_to(docs_dir.parent)),
            namespace=namespace,
            category=category,
        ))
    return topics


def render_index(topics: List[Topic]) -> str:
    desktop = [t for t in topics if t.namespace == "desktop"]
    by_category: Dict[str, List[Topic]] = {name: [] for name in DESKTOP_CATEGORIES}
    for topic in desktop:
        by_category[topic.category].append(topic)

    lines = [
        "# NinjaTrader Developer Documentation Index",
        "",
        f"> Complete index of {len(topics)} topics mirrored from developer.ninjatrader.com",
        "",
        "This index is generated by `build_llms_index.py` from the `docs/` tree.",
        "Do not edit it by hand. For a quick start guide and essential patterns, see `llms.txt`.",
        "",
        "## How to Use This Index",
        "",
        '1. Search for topics: `grep -i "keyword" llms-full.txt`',
        "2. Read detailed docs: `cat docs/<namespace>/<filename>`",
        '3. Search in docs: `grep -r "search term" docs/`',
        "",
        "## Statistics",
        "",
    ]

    def pluralize(count: int) -> str:
        return f"{count} topic" + ("s" if count != 1 else "")

    other_namespaces = sorted({t.namespace for t in topics if t.namespace != "desktop"})

    for name in DESKTOP_CATEGORIES:
        lines.append(f"- Desktop / {name}: {pluralize(len(by_category[name]))}")
    for namespace in other_namespaces:
        count = sum(1 for t in topics if t.namespace == namespace)
        heading = NAMESPACE_SECTIONS.get(namespace, namespace)
        lines.append(f"- {heading.split(' (')[0]}: {pluralize(count)}")
    lines.extend(["", "---", ""])

    for name in DESKTOP_CATEGORIES:
        entries = sorted(by_category[name], key=lambda t: t.title.lower())
        if not entries:
            continue
        lines.extend([f"## Desktop SDK — {name}", ""])
        for topic in entries:
            lines.extend([f"### {topic.title}", f"- File: `{topic.path}`", ""])

    for namespace in other_namespaces:
        entries = sorted((t for t in topics if t.namespace == namespace),
                         key=lambda t: t.title.lower())
        lines.extend([f"## {NAMESPACE_SECTIONS.get(namespace, namespace)}", ""])
        for topic in entries:
            lines.extend([f"### {topic.title}", f"- File: `{topic.path}`", ""])

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    base = Path(__file__).parent
    parser.add_argument("--docs-dir", default=str(base / "docs"))
    parser.add_argument("--output", default=str(base / "llms-full.txt"))
    args = parser.parse_args()

    topics = collect_topics(Path(args.docs_dir))
    if not topics:
        print("No topics found -- run scrape_ninjatrader_docs.py first.", file=sys.stderr)
        return 1

    Path(args.output).write_text(render_index(topics), encoding="utf-8")
    print(f"Wrote {args.output} with {len(topics)} topics")
    for namespace in sorted({t.namespace for t in topics}):
        print(f"  {namespace}: {sum(1 for t in topics if t.namespace == namespace)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
